// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RequestdemoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void requestdemo() {
    driver.get("https://www.domaintools.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.xpath("//a[contains(text(),\'Request A Demo\')]")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.xpath("//input[@id=\'FirstName\']")).click();
    driver.findElement(By.xpath("//input[@id=\'FirstName\']")).sendKeys("Антон");
    driver.findElement(By.xpath("//input[@id=\'LastName\']")).sendKeys("Авраменко");
    driver.findElement(By.xpath("//input[@id=\'Email\']")).sendKeys("anton99910@gmail.com");
    driver.findElement(By.xpath("//input[@id=\'Phone\']")).sendKeys("89803295312");
    {
      WebElement dropdown = driver.findElement(By.id("Country"));
      dropdown.findElement(By.xpath("//option[. = 'Russian Federation']")).click();
    }
    driver.findElement(By.xpath("//input[@id=\'Title\']")).click();
    driver.findElement(By.xpath("//input[@id=\'Title\']")).sendKeys("Developer");
    driver.findElement(By.xpath("//input[@id=\'Company\']")).sendKeys("Itmo");
    driver.findElement(By.xpath("//select[@id=\'Contact_Inquiry_Type__c\']")).click();
    {
      WebElement dropdown = driver.findElement(By.id("Contact_Inquiry_Type__c"));
      dropdown.findElement(By.xpath("//option[. = 'Enterprise Security']")).click();
    }
    driver.findElement(By.xpath("//select[@id=\'Contact_Inquiry_Type__c\']")).click();
    driver.findElement(By.xpath("//form[@id=\'mktoForm_2185\']/div[21]/span/button")).click();
    {
      WebElement element = driver.findElement(By.xpath("//form[@id=\'mktoForm_2185\']/div[21]/span/button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//input[@id=\'Email\']")).click();
    driver.findElement(By.xpath("//input[@id=\'Email\']")).sendKeys("242461@niuitmo.ru");
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
  }
}
